services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 15s
      retries: 5
    # restart: unless-stopped
  
  image-generator-app:
    build: ./image-generator
    container_name: cpp-image-generator-app
    volumes:
      - ./images:/images
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      TZ: America/Toronto
    networks:
      - my-network
    # restart: unless-stopped


  feature-extrator-app:
    build: ./feature-extrator
    container_name: cpp-feature-extrator-app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
    networks:
      - my-network
    # restart: unless-stopped

  data-logger-app:
    build: ./data-logger
    container_name: cpp-data-logger-app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
    networks:
      - my-network
    # restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voyis_main
      TZ: America/Toronto
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      
      # Run init SQL only on first-time startup
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  postgres_data: 

networks:
  my-network:
    driver: bridge
